/**
 * Centralized React Query hooks for every backend actor method.
 *
 * Page tasks import the named hooks from here instead of calling the actor
 * directly, so query keys, enabled-guards, and guest fallbacks stay
 * consistent across the app. Mutations invalidate the relevant query keys so
 * the coin balance and feed stay fresh after awards and redemptions.
 */
import { createActor } from "@/backend";
import { COINS_QUERY_KEY } from "@/hooks/useCoins";
import { STREAK_QUERY_KEY } from "@/hooks/useStreak";
import type {
  Achievement,
  CoinAward,
  DailyGoal,
  Ebook,
  FeedContent,
  LeaderboardEntry,
  Lesson,
  Product,
  ProductRedemption,
  Redemption,
  RewardItem,
  UserProfile,
} from "@/types/rewards";
import { useActor } from "@caffeineai/core-infrastructure";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

/** Query keys are colocated here so mutations can invalidate them. */
export const queryKeys = {
  profile: ["profile"] as const,
  feed: (offset: bigint, limit: bigint, category?: string) =>
    ["feed", offset.toString(), limit.toString(), category ?? "all"] as const,
  rewards: ["rewards"] as const,
  leaderboard: ["leaderboard"] as const,
  achievements: ["achievements"] as const,
  earningsHistory: ["earningsHistory"] as const,
  dailyGoal: (date: bigint) => ["dailyGoal", date.toString()] as const,
  products: (offset: bigint, limit: bigint) =>
    ["products", offset.toString(), limit.toString()] as const,
  product: (id: bigint) => ["product", id.toString()] as const,
  ebooks: (offset: bigint, limit: bigint) =>
    ["ebooks", offset.toString(), limit.toString()] as const,
  ebook: (id: bigint) => ["ebook", id.toString()] as const,
  lessons: (offset: bigint, limit: bigint) =>
    ["lessons", offset.toString(), limit.toString()] as const,
  lesson: (id: bigint) => ["lesson", id.toString()] as const,
};

const EMPTY: readonly never[] = [];

/** Profile of the signed-in caller (or `null` for guests). */
export function useProfile() {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.profile,
    queryFn: async (): Promise<UserProfile | null> => {
      if (!actor) return null;
      return actor.getProfile();
    },
    enabled: !isFetching,
  });
}

/** Paginated feed content for the endless scroll.
 *
 * `category` is an optional server-side filter. When omitted (or `"all"`),
 * the backend returns content across all categories. When provided (e.g.
 * `"finance"`), the backend narrows the slice to that category. The backend
 * `getFeedContent(offset, limit, category?)` signature is regenerated by
 * bindgen during the check wave; until then the third argument is forwarded
 * and the actor accepts it once the bindings are refreshed.
 */
export function useFeedContent(
  offset: bigint,
  limit: bigint,
  category?: string,
) {
  const { actor, isFetching } = useActor(createActor);
  const normalized = category && category !== "all" ? category : undefined;
  return useQuery({
    queryKey: queryKeys.feed(offset, limit, normalized),
    queryFn: async (): Promise<FeedContent[]> => {
      if (!actor) return [];
      if (normalized) {
        return actor.getFeedContent(offset, limit, normalized);
      }
      return actor.getFeedContent(offset, limit, null);
    },
    enabled: !isFetching,
  });
}

/** Available redeemable rewards. */
export function useRewards() {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.rewards,
    queryFn: async (): Promise<RewardItem[]> => {
      if (!actor) return [];
      return actor.getRewards();
    },
    enabled: !isFetching,
  });
}

/** Weekly leaderboard entries. */
export function useLeaderboard() {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.leaderboard,
    queryFn: async (): Promise<LeaderboardEntry[]> => {
      if (!actor) return [];
      return actor.getLeaderboard();
    },
    enabled: !isFetching,
  });
}

/** All achievement definitions. */
export function useAchievements() {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.achievements,
    queryFn: async (): Promise<Achievement[]> => {
      if (!actor) return [];
      return actor.getAchievements();
    },
    enabled: !isFetching,
  });
}

/** Earnings history (coin awards) for the signed-in caller. */
export function useEarningsHistory() {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.earningsHistory,
    queryFn: async (): Promise<CoinAward[]> => {
      if (!actor) return [];
      return actor.getEarningsHistory();
    },
    enabled: !isFetching,
  });
}

/** Daily goal for a given date (yyyymmdd integer, per backend `Date` type). */
export function useDailyGoal(date: bigint) {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.dailyGoal(date),
    queryFn: async (): Promise<DailyGoal | null> => {
      if (!actor) return null;
      return actor.getDailyGoal(date);
    },
    enabled: !isFetching,
  });
}

/** Paginated shop products redeemable with coins. */
export function useProducts(offset: bigint, limit: bigint) {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.products(offset, limit),
    queryFn: async (): Promise<Product[]> => {
      if (!actor) return [];
      return actor.getProducts(offset, limit);
    },
    enabled: !isFetching,
  });
}

/** A single shop product by id (or `null` if not found). */
export function useProduct(id: bigint) {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.product(id),
    queryFn: async (): Promise<Product | null> => {
      if (!actor) return null;
      return actor.getProduct(id);
    },
    enabled: !isFetching,
  });
}

/** Paginated ebooks in the Learn library. */
export function useEbooks(offset: bigint, limit: bigint) {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.ebooks(offset, limit),
    queryFn: async (): Promise<Ebook[]> => {
      if (!actor) return [];
      return actor.getEbooks(offset, limit);
    },
    enabled: !isFetching,
  });
}

/** A single ebook by id (or `null` if not found). */
export function useEbook(id: bigint) {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.ebook(id),
    queryFn: async (): Promise<Ebook | null> => {
      if (!actor) return null;
      return actor.getEbook(id);
    },
    enabled: !isFetching,
  });
}

/** Paginated lessons in the Learn library. */
export function useLessons(offset: bigint, limit: bigint) {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.lessons(offset, limit),
    queryFn: async (): Promise<Lesson[]> => {
      if (!actor) return [];
      return actor.getLessons(offset, limit);
    },
    enabled: !isFetching,
  });
}

/** A single lesson by id (or `null` if not found). */
export function useLesson(id: bigint) {
  const { actor, isFetching } = useActor(createActor);
  return useQuery({
    queryKey: queryKeys.lesson(id),
    queryFn: async (): Promise<Lesson | null> => {
      if (!actor) return null;
      return actor.getLesson(id);
    },
    enabled: !isFetching,
  });
}

/** Award coins for a scroll milestone. Invalidates wallet + streak. */
export function useRecordScrollMilestone() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (args: { sessionId: bigint; milestone: bigint }) => {
      if (!actor) throw new Error("Backend actor not ready");
      return actor.recordScrollMilestone(args.sessionId, args.milestone);
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: COINS_QUERY_KEY });
      void queryClient.invalidateQueries({ queryKey: STREAK_QUERY_KEY });
      void queryClient.invalidateQueries({
        queryKey: queryKeys.earningsHistory,
      });
      // Milestone awards contribute to the daily goal, so invalidate every
      // dailyGoal entry (prefix match) to refresh the progress bar.
      void queryClient.invalidateQueries({
        queryKey: ["dailyGoal"],
      });
    },
  });
}

/** Redeem a reward by id. Invalidates wallet + rewards on success. */
export function useRedeemReward() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (rewardId: bigint): Promise<Redemption> => {
      if (!actor) throw new Error("Backend actor not ready");
      const result = await actor.redeemReward(rewardId);
      if (result.__kind__ === "err") {
        throw new Error(result.err);
      }
      return result.ok;
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: COINS_QUERY_KEY });
      void queryClient.invalidateQueries({ queryKey: queryKeys.rewards });
    },
  });
}

/** Redeem a shop product by id. Invalidates wallet + products on success. */
export function useRedeemProduct() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (productId: bigint): Promise<ProductRedemption> => {
      if (!actor) throw new Error("Backend actor not ready");
      const result = await actor.redeemProduct(productId);
      if (result.__kind__ === "err") {
        throw new Error(result.err);
      }
      return result.ok;
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: COINS_QUERY_KEY });
      void queryClient.invalidateQueries({ queryKey: ["products"] });
      void queryClient.invalidateQueries({ queryKey: ["product"] });
    },
  });
}

/** Sign in (or register) the caller with a chosen username. */
export function useSignIn() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (username: string): Promise<UserProfile> => {
      if (!actor) throw new Error("Backend actor not ready");
      return actor.signIn(username);
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: queryKeys.profile });
      void queryClient.invalidateQueries({ queryKey: COINS_QUERY_KEY });
      void queryClient.invalidateQueries({ queryKey: STREAK_QUERY_KEY });
    },
  });
}

export { EMPTY };
