/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AchievementId = IDL.Nat;
export const Achievement = IDL.Record({
  'id' : AchievementId,
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'unlockedThreshold' : IDL.Nat,
});
export const Date = IDL.Int;
export const DailyGoal = IDL.Record({
  'date' : Date,
  'completed' : IDL.Bool,
  'earnedCoins' : IDL.Nat,
  'targetCoins' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const CoinAward = IDL.Record({
  'id' : IDL.Nat,
  'sourceSessionId' : IDL.Nat,
  'timestamp' : Timestamp,
  'amount' : IDL.Nat,
  'reason' : IDL.Text,
});
export const Ebook = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fullText' : IDL.Text,
  'author' : IDL.Text,
  'category' : IDL.Text,
  'coverUrl' : IDL.Text,
});
export const FeedContentType = IDL.Variant({
  'finance' : IDL.Null,
  'reel' : IDL.Null,
  'article' : IDL.Null,
  'ebook' : IDL.Null,
  'ainews' : IDL.Null,
  'lesson' : IDL.Null,
  'image' : IDL.Null,
  'product' : IDL.Null,
  'funfact' : IDL.Null,
});
export const FeedContent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'contentType' : FeedContentType,
  'body' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const UserId = IDL.Principal;
export const LeaderboardEntry = IDL.Record({
  'weeklyEarnings' : IDL.Nat,
  'username' : IDL.Text,
  'rank' : IDL.Nat,
  'user' : UserId,
});
export const LessonDifficulty = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'difficulty' : LessonDifficulty,
  'description' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceCoins' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'username' : IDL.Text,
  'joinDate' : Date,
  'totalCoins' : IDL.Nat,
  'lifetimeEarnings' : IDL.Nat,
  'lastActiveDate' : Date,
  'todayEarnings' : IDL.Nat,
  'achievements' : IDL.Vec(AchievementId),
  'streakFreezeCount' : IDL.Nat,
  'streakCount' : IDL.Nat,
});
export const RewardItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : IDL.Text,
  'coinPrice' : IDL.Nat,
});
export const RewardsError = IDL.Variant({
  'rewardNotFound' : IDL.Null,
  'userNotFound' : IDL.Null,
  'notAuthorized' : IDL.Null,
  'alreadyRedeemed' : IDL.Null,
  'invalidInput' : IDL.Null,
  'notFound' : IDL.Null,
  'insufficientCoins' : IDL.Null,
  'invalidMilestone' : IDL.Null,
});
export const AwardResult = IDL.Variant({
  'ok' : CoinAward,
  'err' : RewardsError,
});
export const ProductRedemption = IDL.Record({
  'id' : IDL.Nat,
  'redeemedAt' : Timestamp,
  'userId' : UserId,
  'productId' : IDL.Nat,
});
export const RedeemProductResult = IDL.Variant({
  'ok' : ProductRedemption,
  'err' : RewardsError,
});
export const RedemptionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'fulfilled' : IDL.Null,
  'failed' : IDL.Null,
});
export const Redemption = IDL.Record({
  'id' : IDL.Nat,
  'status' : RedemptionStatus,
  'userId' : UserId,
  'rewardId' : IDL.Nat,
  'timestamp' : Timestamp,
  'coinsDeducted' : IDL.Nat,
});
export const RedeemResult = IDL.Variant({
  'ok' : Redemption,
  'err' : RewardsError,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyGoal' : IDL.Func([Date], [IDL.Opt(DailyGoal)], []),
  'getEarningsHistory' : IDL.Func([], [IDL.Vec(CoinAward)], []),
  'getEbook' : IDL.Func([IDL.Nat], [IDL.Opt(Ebook)], ['query']),
  'getEbooks' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Ebook)], ['query']),
  'getFeedContent' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Vec(FeedContent)],
      ['query'],
    ),
  'getFeedContentByCategory' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(FeedContent)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getLesson' : IDL.Func([IDL.Nat], [IDL.Opt(Lesson)], ['query']),
  'getLessons' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Lesson)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getRewards' : IDL.Func([], [IDL.Vec(RewardItem)], ['query']),
  'getStreak' : IDL.Func(
      [],
      [
        IDL.Record({
          'lastActiveDate' : Date,
          'streakFreezeCount' : IDL.Nat,
          'streakCount' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getWallet' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCoins' : IDL.Nat,
          'lifetimeEarnings' : IDL.Nat,
          'todayEarnings' : IDL.Nat,
        }),
      ],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordScrollMilestone' : IDL.Func([IDL.Nat, IDL.Nat], [AwardResult], []),
  'redeemProduct' : IDL.Func([IDL.Nat], [RedeemProductResult], []),
  'redeemReward' : IDL.Func([IDL.Nat], [RedeemResult], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'signIn' : IDL.Func([IDL.Text], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AchievementId = IDL.Nat;
  const Achievement = IDL.Record({
    'id' : AchievementId,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'unlockedThreshold' : IDL.Nat,
  });
  const Date = IDL.Int;
  const DailyGoal = IDL.Record({
    'date' : Date,
    'completed' : IDL.Bool,
    'earnedCoins' : IDL.Nat,
    'targetCoins' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const CoinAward = IDL.Record({
    'id' : IDL.Nat,
    'sourceSessionId' : IDL.Nat,
    'timestamp' : Timestamp,
    'amount' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const Ebook = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fullText' : IDL.Text,
    'author' : IDL.Text,
    'category' : IDL.Text,
    'coverUrl' : IDL.Text,
  });
  const FeedContentType = IDL.Variant({
    'finance' : IDL.Null,
    'reel' : IDL.Null,
    'article' : IDL.Null,
    'ebook' : IDL.Null,
    'ainews' : IDL.Null,
    'lesson' : IDL.Null,
    'image' : IDL.Null,
    'product' : IDL.Null,
    'funfact' : IDL.Null,
  });
  const FeedContent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'contentType' : FeedContentType,
    'body' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const LeaderboardEntry = IDL.Record({
    'weeklyEarnings' : IDL.Nat,
    'username' : IDL.Text,
    'rank' : IDL.Nat,
    'user' : UserId,
  });
  const LessonDifficulty = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'difficulty' : LessonDifficulty,
    'description' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceCoins' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'username' : IDL.Text,
    'joinDate' : Date,
    'totalCoins' : IDL.Nat,
    'lifetimeEarnings' : IDL.Nat,
    'lastActiveDate' : Date,
    'todayEarnings' : IDL.Nat,
    'achievements' : IDL.Vec(AchievementId),
    'streakFreezeCount' : IDL.Nat,
    'streakCount' : IDL.Nat,
  });
  const RewardItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : IDL.Text,
    'coinPrice' : IDL.Nat,
  });
  const RewardsError = IDL.Variant({
    'rewardNotFound' : IDL.Null,
    'userNotFound' : IDL.Null,
    'notAuthorized' : IDL.Null,
    'alreadyRedeemed' : IDL.Null,
    'invalidInput' : IDL.Null,
    'notFound' : IDL.Null,
    'insufficientCoins' : IDL.Null,
    'invalidMilestone' : IDL.Null,
  });
  const AwardResult = IDL.Variant({ 'ok' : CoinAward, 'err' : RewardsError });
  const ProductRedemption = IDL.Record({
    'id' : IDL.Nat,
    'redeemedAt' : Timestamp,
    'userId' : UserId,
    'productId' : IDL.Nat,
  });
  const RedeemProductResult = IDL.Variant({
    'ok' : ProductRedemption,
    'err' : RewardsError,
  });
  const RedemptionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'fulfilled' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Redemption = IDL.Record({
    'id' : IDL.Nat,
    'status' : RedemptionStatus,
    'userId' : UserId,
    'rewardId' : IDL.Nat,
    'timestamp' : Timestamp,
    'coinsDeducted' : IDL.Nat,
  });
  const RedeemResult = IDL.Variant({ 'ok' : Redemption, 'err' : RewardsError });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyGoal' : IDL.Func([Date], [IDL.Opt(DailyGoal)], []),
    'getEarningsHistory' : IDL.Func([], [IDL.Vec(CoinAward)], []),
    'getEbook' : IDL.Func([IDL.Nat], [IDL.Opt(Ebook)], ['query']),
    'getEbooks' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Ebook)], ['query']),
    'getFeedContent' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Vec(FeedContent)],
        ['query'],
      ),
    'getFeedContentByCategory' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(FeedContent)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getLesson' : IDL.Func([IDL.Nat], [IDL.Opt(Lesson)], ['query']),
    'getLessons' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Lesson)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getRewards' : IDL.Func([], [IDL.Vec(RewardItem)], ['query']),
    'getStreak' : IDL.Func(
        [],
        [
          IDL.Record({
            'lastActiveDate' : Date,
            'streakFreezeCount' : IDL.Nat,
            'streakCount' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getWallet' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCoins' : IDL.Nat,
            'lifetimeEarnings' : IDL.Nat,
            'todayEarnings' : IDL.Nat,
          }),
        ],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordScrollMilestone' : IDL.Func([IDL.Nat, IDL.Nat], [AwardResult], []),
    'redeemProduct' : IDL.Func([IDL.Nat], [RedeemProductResult], []),
    'redeemReward' : IDL.Func([IDL.Nat], [RedeemResult], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'signIn' : IDL.Func([IDL.Text], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };