/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : AchievementId,
  'title' : string,
  'icon' : string,
  'description' : string,
  'unlockedThreshold' : bigint,
}
export type AchievementId = bigint;
export type AwardResult = { 'ok' : CoinAward } |
  { 'err' : RewardsError };
export interface Cell { 'value' : Value, 'name' : string }
export interface CoinAward {
  'id' : bigint,
  'sourceSessionId' : bigint,
  'timestamp' : Timestamp,
  'amount' : bigint,
  'reason' : string,
}
export interface DailyGoal {
  'date' : Date,
  'completed' : boolean,
  'earnedCoins' : bigint,
  'targetCoins' : bigint,
}
export type Date = bigint;
export interface Ebook {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'fullText' : string,
  'author' : string,
  'category' : string,
  'coverUrl' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FeedContent {
  'id' : bigint,
  'title' : string,
  'contentType' : FeedContentType,
  'body' : string,
  'imageUrl' : string,
  'category' : string,
}
export type FeedContentType = { 'finance' : null } |
  { 'reel' : null } |
  { 'article' : null } |
  { 'ebook' : null } |
  { 'ainews' : null } |
  { 'lesson' : null } |
  { 'image' : null } |
  { 'product' : null } |
  { 'funfact' : null };
export interface LeaderboardEntry {
  'weeklyEarnings' : bigint,
  'username' : string,
  'rank' : bigint,
  'user' : UserId,
}
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'difficulty' : LessonDifficulty,
  'description' : string,
  'steps' : Array<string>,
  'category' : string,
}
export type LessonDifficulty = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface Product {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'priceCoins' : bigint,
}
export interface ProductRedemption {
  'id' : bigint,
  'redeemedAt' : Timestamp,
  'userId' : UserId,
  'productId' : bigint,
}
export type RedeemProductResult = { 'ok' : ProductRedemption } |
  { 'err' : RewardsError };
export type RedeemResult = { 'ok' : Redemption } |
  { 'err' : RewardsError };
export interface Redemption {
  'id' : bigint,
  'status' : RedemptionStatus,
  'userId' : UserId,
  'rewardId' : bigint,
  'timestamp' : Timestamp,
  'coinsDeducted' : bigint,
}
export type RedemptionStatus = { 'pending' : null } |
  { 'fulfilled' : null } |
  { 'failed' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface RewardItem {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'category' : string,
  'image' : string,
  'coinPrice' : bigint,
}
export type RewardsError = { 'rewardNotFound' : null } |
  { 'userNotFound' : null } |
  { 'notAuthorized' : null } |
  { 'alreadyRedeemed' : null } |
  { 'invalidInput' : null } |
  { 'notFound' : null } |
  { 'insufficientCoins' : null } |
  { 'invalidMilestone' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'principal' : UserId,
  'username' : string,
  'joinDate' : Date,
  'totalCoins' : bigint,
  'lifetimeEarnings' : bigint,
  'lastActiveDate' : Date,
  'todayEarnings' : bigint,
  'achievements' : Array<AchievementId>,
  'streakFreezeCount' : bigint,
  'streakCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getAchievements' : ActorMethod<[], Array<Achievement>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyGoal' : ActorMethod<[Date], [] | [DailyGoal]>,
  'getEarningsHistory' : ActorMethod<[], Array<CoinAward>>,
  'getEbook' : ActorMethod<[bigint], [] | [Ebook]>,
  'getEbooks' : ActorMethod<[bigint, bigint], Array<Ebook>>,
  'getFeedContent' : ActorMethod<
    [bigint, bigint, [] | [string]],
    Array<FeedContent>
  >,
  'getFeedContentByCategory' : ActorMethod<
    [string, bigint, bigint],
    Array<FeedContent>
  >,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getLesson' : ActorMethod<[bigint], [] | [Lesson]>,
  'getLessons' : ActorMethod<[bigint, bigint], Array<Lesson>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getRewards' : ActorMethod<[], Array<RewardItem>>,
  'getStreak' : ActorMethod<
    [],
    {
      'lastActiveDate' : Date,
      'streakFreezeCount' : bigint,
      'streakCount' : bigint,
    }
  >,
  'getWallet' : ActorMethod<
    [],
    {
      'totalCoins' : bigint,
      'lifetimeEarnings' : bigint,
      'todayEarnings' : bigint,
    }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordScrollMilestone' : ActorMethod<[bigint, bigint], AwardResult>,
  'redeemProduct' : ActorMethod<[bigint], RedeemProductResult>,
  'redeemReward' : ActorMethod<[bigint], RedeemResult>,
  'schema' : ActorMethod<[], string>,
  'signIn' : ActorMethod<[string], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];