/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface ProductRedemption {
    id: bigint;
    redeemedAt: Timestamp;
    userId: UserId;
    productId: bigint;
}
export interface LeaderboardEntry {
    weeklyEarnings: bigint;
    username: string;
    rank: bigint;
    user: UserId;
}
export type Timestamp = bigint;
export interface CoinAward {
    id: bigint;
    sourceSessionId: bigint;
    timestamp: Timestamp;
    amount: bigint;
    reason: string;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type RedeemProductResult = {
    __kind__: "ok";
    ok: ProductRedemption;
} | {
    __kind__: "err";
    err: RewardsError;
};
export interface RewardItem {
    id: bigint;
    title: string;
    description: string;
    category: string;
    image: string;
    coinPrice: bigint;
}
export interface Achievement {
    id: AchievementId;
    title: string;
    icon: string;
    description: string;
    unlockedThreshold: bigint;
}
export type AwardResult = {
    __kind__: "ok";
    ok: CoinAward;
} | {
    __kind__: "err";
    err: RewardsError;
};
export interface FeedContent {
    id: bigint;
    title: string;
    contentType: FeedContentType;
    body: string;
    imageUrl: string;
    category: string;
}
export interface Lesson {
    id: bigint;
    title: string;
    difficulty: LessonDifficulty;
    description: string;
    steps: Array<string>;
    category: string;
}
export interface DailyGoal {
    date: Date_;
    completed: boolean;
    earnedCoins: bigint;
    targetCoins: bigint;
}
export type RedeemResult = {
    __kind__: "ok";
    ok: Redemption;
} | {
    __kind__: "err";
    err: RewardsError;
};
export interface Cell {
    value: Value;
    name: string;
}
export interface Ebook {
    id: bigint;
    title: string;
    description: string;
    fullText: string;
    author: string;
    category: string;
    coverUrl: string;
}
export type AchievementId = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export type Date_ = bigint;
export interface Redemption {
    id: bigint;
    status: RedemptionStatus;
    userId: UserId;
    rewardId: bigint;
    timestamp: Timestamp;
    coinsDeducted: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type UserId = Principal;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface UserProfile {
    principal: UserId;
    username: string;
    joinDate: Date_;
    totalCoins: bigint;
    lifetimeEarnings: bigint;
    lastActiveDate: Date_;
    todayEarnings: bigint;
    achievements: Array<AchievementId>;
    streakFreezeCount: bigint;
    streakCount: bigint;
}
export interface Product {
    id: bigint;
    title: string;
    description: string;
    imageUrl: string;
    category: string;
    priceCoins: bigint;
}
export enum FeedContentType {
    finance = "finance",
    reel = "reel",
    article = "article",
    ebook = "ebook",
    ainews = "ainews",
    lesson = "lesson",
    image = "image",
    product = "product",
    funfact = "funfact"
}
export enum LessonDifficulty {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum RedemptionStatus {
    pending = "pending",
    fulfilled = "fulfilled",
    failed = "failed"
}
export enum RewardsError {
    rewardNotFound = "rewardNotFound",
    userNotFound = "userNotFound",
    notAuthorized = "notAuthorized",
    alreadyRedeemed = "alreadyRedeemed",
    invalidInput = "invalidInput",
    notFound = "notFound",
    insufficientCoins = "insufficientCoins",
    invalidMilestone = "invalidMilestone"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    execute(qJson: string): Promise<Result>;
    getAchievements(): Promise<Array<Achievement>>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyGoal(date: Date_): Promise<DailyGoal | null>;
    getEarningsHistory(): Promise<Array<CoinAward>>;
    getEbook(id: bigint): Promise<Ebook | null>;
    getEbooks(offset: bigint, limit: bigint): Promise<Array<Ebook>>;
    getFeedContent(offset: bigint, limit: bigint, category: string | null): Promise<Array<FeedContent>>;
    getFeedContentByCategory(category: string, offset: bigint, limit: bigint): Promise<Array<FeedContent>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getLesson(id: bigint): Promise<Lesson | null>;
    getLessons(offset: bigint, limit: bigint): Promise<Array<Lesson>>;
    getProduct(id: bigint): Promise<Product | null>;
    getProducts(offset: bigint, limit: bigint): Promise<Array<Product>>;
    getProfile(): Promise<UserProfile | null>;
    getRewards(): Promise<Array<RewardItem>>;
    getStreak(): Promise<{
        lastActiveDate: Date_;
        streakFreezeCount: bigint;
        streakCount: bigint;
    }>;
    getWallet(): Promise<{
        totalCoins: bigint;
        lifetimeEarnings: bigint;
        todayEarnings: bigint;
    }>;
    isCallerAdmin(): Promise<boolean>;
    recordScrollMilestone(sessionId: bigint, milestone: bigint): Promise<AwardResult>;
    redeemProduct(productId: bigint): Promise<RedeemProductResult>;
    redeemReward(rewardId: bigint): Promise<RedeemResult>;
    schema(): Promise<string>;
    signIn(username: string): Promise<UserProfile>;
}
import type { AwardResult as _AwardResult, Cell as _Cell, CoinAward as _CoinAward, DailyGoal as _DailyGoal, Ebook as _Ebook, Error as _Error, FeedContent as _FeedContent, FeedContentType as _FeedContentType, Lesson as _Lesson, LessonDifficulty as _LessonDifficulty, Product as _Product, ProductRedemption as _ProductRedemption, RedeemProductResult as _RedeemProductResult, RedeemResult as _RedeemResult, Redemption as _Redemption, RedemptionStatus as _RedemptionStatus, Result as _Result, Result__1 as _Result__1, RewardsError as _RewardsError, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyGoal(arg0: Date_): Promise<DailyGoal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyGoal(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyGoal(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEarningsHistory(): Promise<Array<CoinAward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEarningsHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEarningsHistory();
            return result;
        }
    }
    async getEbook(arg0: bigint): Promise<Ebook | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEbook(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEbook(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEbooks(arg0: bigint, arg1: bigint): Promise<Array<Ebook>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEbooks(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEbooks(arg0, arg1);
            return result;
        }
    }
    async getFeedContent(arg0: bigint, arg1: bigint, arg2: string | null): Promise<Array<FeedContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedContent(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedContent(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedContentByCategory(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<FeedContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedContentByCategory(arg0, arg1, arg2);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedContentByCategory(arg0, arg1, arg2);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getLesson(arg0: bigint): Promise<Lesson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessons(arg0: bigint, arg1: bigint): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessons(arg0, arg1);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessons(arg0, arg1);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(arg0: bigint, arg1: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts(arg0, arg1);
            return result;
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRewards(): Promise<Array<RewardItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewards();
            return result;
        }
    }
    async getStreak(): Promise<{
        lastActiveDate: Date_;
        streakFreezeCount: bigint;
        streakCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreak();
            return result;
        }
    }
    async getWallet(): Promise<{
        totalCoins: bigint;
        lifetimeEarnings: bigint;
        todayEarnings: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordScrollMilestone(arg0: bigint, arg1: bigint): Promise<AwardResult> {
        if (this.processError) {
            try {
                const result = await this.actor.recordScrollMilestone(arg0, arg1);
                return from_candid_AwardResult_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordScrollMilestone(arg0, arg1);
            return from_candid_AwardResult_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async redeemProduct(arg0: bigint): Promise<RedeemProductResult> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemProduct(arg0);
                return from_candid_RedeemProductResult_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemProduct(arg0);
            return from_candid_RedeemProductResult_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async redeemReward(arg0: bigint): Promise<RedeemResult> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemReward(arg0);
                return from_candid_RedeemResult_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemReward(arg0);
            return from_candid_RedeemResult_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async signIn(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.signIn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signIn(arg0);
            return result;
        }
    }
}
function from_candid_AwardResult_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AwardResult): AwardResult {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_FeedContentType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedContentType): FeedContentType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_FeedContent_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedContent): FeedContent {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_LessonDifficulty_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LessonDifficulty): LessonDifficulty {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Lesson_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Lesson {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_RedeemProductResult_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedeemProductResult): RedeemProductResult {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_RedeemResult_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedeemResult): RedeemResult {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_RedemptionStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedemptionStatus): RedemptionStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Redemption_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Redemption): Redemption {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RewardsError_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RewardsError): RewardsError {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyGoal]): DailyGoal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Ebook]): Ebook | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lesson]): Lesson | null {
    return value.length === 0 ? null : from_candid_Lesson_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n13(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    contentType: _FeedContentType;
    body: string;
    imageUrl: string;
    category: string;
}): {
    id: bigint;
    title: string;
    contentType: FeedContentType;
    body: string;
    imageUrl: string;
    category: string;
} {
    return {
        id: value.id,
        title: value.title,
        contentType: from_candid_FeedContentType_n23(_uploadFile, _downloadFile, value.contentType),
        body: value.body,
        imageUrl: value.imageUrl,
        category: value.category
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    difficulty: _LessonDifficulty;
    description: string;
    steps: Array<string>;
    category: string;
}): {
    id: bigint;
    title: string;
    difficulty: LessonDifficulty;
    description: string;
    steps: Array<string>;
    category: string;
} {
    return {
        id: value.id,
        title: value.title,
        difficulty: from_candid_LessonDifficulty_n28(_uploadFile, _downloadFile, value.difficulty),
        description: value.description,
        steps: value.steps,
        category: value.category
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RedemptionStatus;
    userId: _UserId;
    rewardId: bigint;
    timestamp: _Timestamp;
    coinsDeducted: bigint;
}): {
    id: bigint;
    status: RedemptionStatus;
    userId: UserId;
    rewardId: bigint;
    timestamp: Timestamp;
    coinsDeducted: bigint;
} {
    return {
        id: value.id,
        status: from_candid_RedemptionStatus_n43(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        rewardId: value.rewardId,
        timestamp: value.timestamp,
        coinsDeducted: value.coinsDeducted
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n9(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    finance: null;
} | {
    reel: null;
} | {
    article: null;
} | {
    ebook: null;
} | {
    ainews: null;
} | {
    lesson: null;
} | {
    image: null;
} | {
    product: null;
} | {
    funfact: null;
}): FeedContentType {
    return "finance" in value ? FeedContentType.finance : "reel" in value ? FeedContentType.reel : "article" in value ? FeedContentType.article : "ebook" in value ? FeedContentType.ebook : "ainews" in value ? FeedContentType.ainews : "lesson" in value ? FeedContentType.lesson : "image" in value ? FeedContentType.image : "product" in value ? FeedContentType.product : "funfact" in value ? FeedContentType.funfact : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): LessonDifficulty {
    return "intermediate" in value ? LessonDifficulty.intermediate : "beginner" in value ? LessonDifficulty.beginner : "advanced" in value ? LessonDifficulty.advanced : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CoinAward;
} | {
    err: _RewardsError;
}): {
    __kind__: "ok";
    ok: CoinAward;
} | {
    __kind__: "err";
    err: RewardsError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_RewardsError_n35(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rewardNotFound: null;
} | {
    userNotFound: null;
} | {
    notAuthorized: null;
} | {
    alreadyRedeemed: null;
} | {
    invalidInput: null;
} | {
    notFound: null;
} | {
    insufficientCoins: null;
} | {
    invalidMilestone: null;
}): RewardsError {
    return "rewardNotFound" in value ? RewardsError.rewardNotFound : "userNotFound" in value ? RewardsError.userNotFound : "notAuthorized" in value ? RewardsError.notAuthorized : "alreadyRedeemed" in value ? RewardsError.alreadyRedeemed : "invalidInput" in value ? RewardsError.invalidInput : "notFound" in value ? RewardsError.notFound : "insufficientCoins" in value ? RewardsError.insufficientCoins : "invalidMilestone" in value ? RewardsError.invalidMilestone : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ProductRedemption;
} | {
    err: _RewardsError;
}): {
    __kind__: "ok";
    ok: ProductRedemption;
} | {
    __kind__: "err";
    err: RewardsError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_RewardsError_n35(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Redemption;
} | {
    err: _RewardsError;
}): {
    __kind__: "ok";
    ok: Redemption;
} | {
    __kind__: "err";
    err: RewardsError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Redemption_n41(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_RewardsError_n35(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    fulfilled: null;
} | {
    failed: null;
}): RedemptionStatus {
    return "pending" in value ? RedemptionStatus.pending : "fulfilled" in value ? RedemptionStatus.fulfilled : "failed" in value ? RedemptionStatus.failed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedContent>): Array<FeedContent> {
    return value.map((x)=>from_candid_FeedContent_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lesson>): Array<Lesson> {
    return value.map((x)=>from_candid_Lesson_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n10(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
